hostname = api.m.jd.com,huyaimg.msstatic.com,livewebbs2pcdn.msstatic.com
^https?:\/\/livewebbs2pcdn\.msstatic\.com\/bannerconfig\/ url reject-200
^https?:\/\/((25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\.){3}(25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d):\d{5}\/livewebbs2pcdn\.msstatic\.com\/bannerconfig\/ url reject-200
^https:\/\/huyaimg\.msstatic\.com\/cdnimage\/ url reject-200
^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=start url reject-img
