hostname = api.m.jd.com,business.msstatic.com,diy-assets.msstatic.com,livewebbs2.msstatic.com,livewebbs2pcdn.msstatic.com,huyaimg.msstatic.com
#^https?:\/\/livewebbs2pcdn\.msstatic\.com\/bannerconfig\/* url reject-img
^https?:\/\/livewebbs2pcdn\.msstatic\.com\/* url reject-img
#^https?:\/\/((25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\.){3}(25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d):\d{5}\/livewebbs2pcdn\.msstatic\.com\/bannerconfig\/* url reject-img
#^https?:\/\/livewebbs2\.msstatic\.com\/function_component\/* url reject-img
^https?:\/\/livewebbs2\.msstatic\.com\/* url reject-img
#^https?:\/\/business\.msstatic\.com\/advertiser\/* url reject-img
^https?:\/\/business\.msstatic\.com\/* url reject-img
#^https?:\/\/diy\-assets\.msstatic\.com\/hyys\/* url reject-img
^https?:\/\/diy\-assets\.msstatic\.com\/* url reject-img
^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=start url reject-img

^https:\/\/huyaimg\.msstatic\.com\/cdnimage\/ url reject-img


