#
hostname = mappsv5.caixin.com, gateway.caixin.com
^https:\/\/mappsv5\.caixin\.com\/channelv5\/article_ad_ios_info\.json url reject
^https:\/\/gateway\.caixin\.com\/api\/app-api\/adInfoData\/getDateAdAll url reject
^https:\/\/gateway\.caixin\.com\/api\/app-api\/cxAdInfo\/selectIndexAdInfo url reject