hostname = cdnfile1.msstatic.com,m*.amap.com
^https?:\/\/m\d\.amap\.com\/ws\/valueadded\/alimama\/splash_screen\/ url reject
^https?:\/\/cdnfile1\.msstatic\.com\/cdnfile\/appad\/ url reject
#^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=start url reject-img
