hostname = d3plbs0ewhofpw.cloudfront.net, china2021.s3.ap-northeast-2.amazonaws.com

^https:\/\/d3plbs0ewhofpw\.cloudfront\.net\/index\.php\/jsapi\/paywall url script-response-body ft.js

^https:\/\/china2021\.s3\.ap-northeast-2\.amazonaws\.com\/(iosremoteconfig|applaunchschedule)\.json\? url script-response-body ftad.js

#^https:\/\/creatives\.ftacademy\.cn\/ads url reject-img
#^https:\/\/china2021\.s3\.ap\-northeast\-2\.amazonaws\.com\/applaunchschedule\.json\? url reject
#^https:\/\/d3plbs0ewhofpw\.cloudfront\.net\/log\/new_log\.php url reject