hostname = api.tidal.com
^https:\/\/api\.tidal\.com\/v1\/users\/\d+\/subscription\? url script-response-body tidal.js

#^https?:\/\/api\.tidal\.com\/v1\/tracks\/(\d+)\/playbackinfopostpaywall\?&audioquality=HIGH url 302 https://api.tidal.com/v1/tracks/$1/playbackinfopostpaywall?&audioquality=HI_RES

^https?:\/\/api\.tidal\.com\/v1\/tracks\/(\d+)\/playbackinfopostpaywall\? url script-response-body tidalhr.js