hostname = i.weread.qq.com, 101.89.39.29, 101.89.39.40
#^https:\/\/i\.weread\.qq\.com\/(pay\/balance|pay\/memberCardSummary) url script-response-body weread.js
^https:\/\/i\.weread\.qq\.com\/book\/podcasts\? url reject
^https:\/\/i\.weread\.qq\.com\/book\/similar\? url reject
^https:\/\/i\.weread\.qq\.com\/reader\/tips\? url reject
