hostname = dqbam2jv6gg9m.cloudfront.net, creatives.ftacademy.cn
^https:\/\/dqbam2jv6gg9m\.cloudfront\.net\/index\.php\/jsapi\/paywall url script-response-body ft.js
^https:\/\/creatives\.ftacademy\.cn\/ads url reject