# mobile-playpage/track/v3/baseinfo/
# mobile-playpage/view/
# mobile-playpage/playpage/
# mobile/playlist/album/
# nyx/v1/history/query/
# discovery-feed/v3/mix/

hostname = mobile.ximalaya.com,123.161.58.77
^https?:\/\/mobile\.ximalaya\.com\/(mobile\-playpage\/track\/v3\/baseInfo\/|mobile\-playpage\/view\/|mobile\-playpage\/playpage\/|mobile\/playlist\/album\/|nyx\/v1\/history\/query\/|discovery\-feed\/v3\/mix\/) url script-response-body xmly.js

